import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import { cookies } from "next/headers";
import { verifyJwt } from "@/lib/verifyJwt";
import SessionProvider from "@/context/SessionContext";

const prompt = Prompt({ subsets: ["latin"], weight: ['200', '300', '400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const cookiesList = cookies()
  const token: string | undefined = cookiesList.get('access-token')?.value

  let verification = null

  if (token !== undefined) {
    verification = await verifyJwt(token)
  }
  return (
    <html lang="en">
      <body className={`${prompt.className} bg-white dark:bg-black`}>
        <SessionProvider>
          <Navbar verification={verification} />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
